### MAIN PLAYBOOK ###

- name: Configure Web Servers
  hosts: all
  become: true
  
  tasks:
    - name: Import Nginx playbook
      import_tasks: nginx.yml

    - name: Import CloudWatch Agent playbook
      import_tasks: cloudwatchagent.yml


